version: '3.8'

services:
  postgres:
    image: postgres:16
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      - POSTGRES_DB=mothership
      - POSTGRES_USER=mothership
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-mothership_dev}
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d/
    networks:
      - mothership-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mothership -d mothership"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  mothership-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "${MOTHERSHIP_PORT:-7523}:7523"
    environment:
      - MOTHERSHIP_PORT=7523
      - RUST_LOG=${RUST_LOG:-info}
      - JWT_SECRET=${JWT_SECRET}
      - ADMIN_SECRET=${ADMIN_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      # OAuth callback URLs for Docker
      - OAUTH_BASE_URL=http://localhost:7523
      # Database configuration
      - DATABASE_URL=postgresql://mothership:${POSTGRES_PASSWORD:-mothership_dev}@postgres:5432/mothership
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - mothership-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:7523/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  auth-server:
    build:
      context: ./auth-server
      dockerfile: Dockerfile
    ports:
      - "${AUTH_SERVER_PORT:-3001}:3000"
    environment:
      - PORT=3000
      - MOTHERSHIP_API=http://mothership-server:7523
      - NODE_ENV=production
    env_file:
      - .env
    depends_on:
      mothership-server:
        condition: service_healthy
    networks:
      - mothership-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  mothership-network:
    driver: bridge

volumes:
  postgres_data: 