services:
  mothership:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "${MOTHERSHIP_PORT:-7523}:7523"  # API port
      - "${WEB_PORT:-8080}:8080"         # Web UI port
    environment:
      # Server settings
      - MOTHERSHIP_PORT=${MOTHERSHIP_PORT}
      - RUST_LOG=${RUST_LOG}
      - JWT_SECRET=${JWT_SECRET}
      - ADMIN_SECRET=${ADMIN_SECRET}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      # Database settings
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@db:5432/mothership
      # OAuth configuration
      - OAUTH_BASE_URL=https://api.mothershipproject.dev
      - WEB_UI_BASE_URL=https://app.mothershipproject.dev
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
    volumes:
      - ./storage:/app/storage
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:7523/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - mothership-net

  tunnel:
    image: cloudflare/cloudflared:latest
    command: tunnel --config /etc/cloudflared/config.yml run
    volumes:
      - ./mothership-tunnel.yml:/etc/cloudflared/config.yml:ro
      - ~/.cloudflared:/etc/cloudflared/credentials:ro
    depends_on:
      - mothership
    restart: unless-stopped
    networks:
      - mothership-net

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=mothership
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - mothership-net

volumes:
  postgres_data:

networks:
  mothership-net:
    driver: bridge 